# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObectiveCCollectionView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ObectiveCCollectionView
  pod 'AFNetworking'
  
  target 'ObectiveCCollectionViewTests' do
    inherit! :search_paths
    pod 'OCMock'
  end

  target 'ObectiveCCollectionViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
